#!/bin/bash

SSID=$(nmcli device | grep wlp2s0 | awk '{print $4;}')

if [ $SSID = "--" ]; then
	echo "Not connected"
else
	STRENGTH=$(nmcli device wifi | grep $SSID | awk '{print $6;}')
	echo  $SSID  $STRENGTH%
fi

case $BLOCK_BUTTON in
	1) termite -e nmtui ;;
esac

