#!/bin/bash

CEILING="${BLOCK_INSTANCE%/*}"
CEILING="${CEILING:-100}"

STEP="${BLOCK_INSTANCE#*/}"
STEP="${STEP:-5}"

function move_sinks_to_new_default {
    DEFAULT_SINK=$1
    pacmd list-sink-inputs | grep index: | grep -o '[0-9]\+' | while read SINK
    do
        pacmd move-sink-input $SINK $DEFAULT_SINK
    done
}

function set_default_device {
    inc=${1:-1}
    num_devices=$(pacmd list-sinks | grep -c index:)
    sink_arr=($(pacmd list-sinks | grep index: | grep -o '[0-9]\+'))
    default_sink_index=$(( $(pacmd list-sinks | grep index: | grep -no '*' | grep -o '^[0-9]\+') - 1 ))
    default_sink_index=$(( ($default_sink_index + $num_devices + $inc) % $num_devices ))
    default_sink=${sink_arr[$default_sink_index]}
    pacmd set-default-sink $default_sink
    move_sinks_to_new_default $default_sink
}

case $BLOCK_BUTTON in	# Ponymix auto-prints volume so >/dev/null
  1) set_default_device ;;
  2) (pavucontrol &) ;;
  3) ponymix toggle >/dev/null;;				# Right Click
  4) ponymix --max-volume $CEILING increase $STEP >/dev/null;;	# Scroll Up
  5) ponymix --max-volume $CEILING decrease $STEP >/dev/null;;	# Scroll Down
esac

function print {
	VOL="$(ponymix get-volume)"

	if [[ $VOL -lt 10 ]]; then
		STATE="  ${VOL}";
	elif [[ $VOL -lt 50 ]]; then
		STATE="  ${VOL}";
	else
		STATE="  ${VOL}";
	fi

	if ponymix is-muted; then
		
		STATE="ﱝ"
		echo " $STATE "
	else
		NAME=$(pacmd list-sinks |\
			awk '/^\s*\*/{f=1}/^\s*index:/{f=0}f' |\
			grep "device.description" |\
			head -n1 |\
			sed 's/.*= "\(.*\)".*/\1/')
		case $NAME in 
			"Z113") echo "$STATE<span size='x-small'></span> 蓼 $NAME 蓼 " ;;
			"G533 Headset") echo "$STATE<span size='x-small'></span>  $NAME " ;;
			*) echo "$STATE<span size='x-small'></span> $NAME " ;;
		esac
	fi
}

print
