#!/bin/bash

weather=$(curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=EUR|AT|AU007|INNSBRUCK" | perl -ne 'use utf8; if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; my @values=split(":",$1);binmode(STDOUT, ":utf8");print"$values[0]"}')

temp=$(curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=EUR|AT|AU007|INNSBRUCK" | perl -ne 'use utf8; if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; my @values=split(":",$1);binmode(STDOUT, ":utf8");print"$values[1]"}')

SYMBOL=""

if [[ "$weather" = "Clear" ]] || [[  "$weather" = "Mostly Clear" ]] || [[ "$weather" = "Sunny" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Cloudy" ]] || [[ "$weather" = "Intermittent Clouds" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Hazy Moonlight" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Cloudy W/ Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Cloudy W/ T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ Flurries" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ Snow" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Flurries" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Sunny W/ Flurries" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Snow" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Ice" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Sleet" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Freezing Rain" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Rain and Snow" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Cold" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Windy" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Sunny W/ Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Sunny W/ T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Rain" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Cloudy" ]] || [[ "$weather" = "Mostly Cloudy" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Dreary (Overcast)" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Fog" ]]; then
	SYMBOL=''
fi

echo "<span font = \"Weather Icons\"><b>${SYMBOL}</b></span> ${weather} <span font = \"Weather Icons\"><b></b></span><b><i>${temp}</i></b>"
