#!/bin/bash

weather=$(curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=EUR|AT|AU007|INNSBRUCK" | perl -ne 'use utf8; if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; my @values=split(":",$1);binmode(STDOUT, ":utf8");print"$values[0]"}')

temp=$(curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=EUR|AT|AU007|INNSBRUCK" | perl -ne 'use utf8; if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; my @values=split(":",$1);binmode(STDOUT, ":utf8");print"$values[1]"}')

temp2=${temp//C}
SYMBOL=""

if [[ "$weather" = "Clear" ]] || [[  "$weather" = "Mostly Clear" ]] || [[ "$weather" = "Sunny" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Sunny" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Cloudy" ]] || [[ "$weather" = "Intermittent Clouds" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Hazy Moonlight" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Cloudy W/ Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Cloudy W/ T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ Flurries" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ Snow" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Flurries" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Rain And Snow" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Sunny W/ Flurries" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Snow" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Ice" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Sleet" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Freezing Rain" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Rain and Snow" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Cold" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Windy" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Sunny W/ Showers" ]]; then
	SYMBOL=''
elif [[ "$weather" = "T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Mostly Cloudy W/ T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Partly Sunny W/ T-Storms" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Rain" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Cloudy" ]] || [[ "$weather" = "Mostly Cloudy" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Dreary (Overcast)" ]]; then
	SYMBOL=''
elif [[ "$weather" = "Fog" ]]; then
	SYMBOL=''
fi

echo " <span font = \"Weather Icons\"><b>${SYMBOL}</b></span> <i>${weather}</i> <span font = \"Weather Icons\"></span>${temp2}<small>°C</small>"

echo $temp2

# color

if [[ $temp2 -le 0 ]]; then
	echo "#71ccd0"
elif [[ $temp2 -le 3 ]]; then
	echo "#c6de86"
elif [[ $temp2 -le 6 ]]; then
	echo "#dde566"
elif [[ $temp2 -le 10 ]]; then
	echo "#ffe900"
elif [[ $temp2 -le 15 ]]; then
	echo "#ffbf0f"
elif [[ $temp2 -le 20 ]]; then
	echo "#fcad17"
elif [[ $temp2 -le 25 ]]; then
	echo "#f47321"
elif [[ $temp2 -gt 25 ]]; then
	echo "#ff0000"
fi
