#!/bin/bash
INTERFACE=$(ip link show | grep "state UP" | head -n 1 | awk '{print $2;}' | sed s'/.$//')
#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

SSID=$(iw dev $INTERFACE link | grep SSID | awk '{print $2;}')
DEVNAME=$(echo "$INTERFACE" | cut -c-2 )

if [[ "$DEVNAME" = "" ]]; then
	echo " 睊 "
elif [[ "$DEVNAME" = "en" ]]; then
	echo "  <i>Wired</i> "
elif [[ "$DEVNAME" = "wl" ]]; then
	echo "   <i>$SSID</i> 說 $QUALITY<span size='x-small'></span> "
else 
	echo " Unknown device "
fi
