#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

#INTERFACE="${BLOCK_INSTANCE:-wlp2s0}"
INTERFACE=$(iw dev | grep Interface | head -n 1 | awk '{print $2;}')
#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

SSID=$(iw dev $INTERFACE link | grep SSID | awk '{print $2;}')
 
if [[ "$SSID" = "--" ]]; then
	echo "Not connected"
elif [[ "$SSID" = "Wired" ]]; then
	echo "  <i> Wired </i>"
else
	echo " <i>$SSID</i>  $QUALITY<small></small>"
fi

case $BLOCK_BUTTON in
	1) (nmtui &) && disown ;;
esac

echo $QUALITY%

# color
#if [[ $QUALITY -ge 80 ]]; then
#    echo "#00FF00"
#elif [[ $QUALITY -lt 80 ]]; then
#    echo "#FFF600"
#elif [[ $QUALITY -lt 60 ]]; then
#    echo "#FFAE00"
#elif [[ $QUALITY -lt 40 ]]; then
#    echo "#FF0000"
#fi
