export DOTFILES=~/dotfiles
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
export EDITOR=nvim
export VISUAL=nvim
export TERM=termite
export GTK_THEME=deepin-dark

export CAPACITOR_ANDROID_STUDIO_PATH=/usr/bin/android-studio
export ANDROID_SDK_ROOT=~/Android/Sdk

source ~/.antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search

antigen theme gnzh

antigen apply

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=4'

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lha --color=auto'

alias inst='yay -S'
alias uinst='yay -Rsnc'
alias search='yay -Ss'

alias dd='sudo dd status=progress bs=4M'

alias i3conf="vim $DOTFILES/config/i3/config"
alias cddot="cd $DOTFILES"
alias ccmake='cmake . && make'
alias x='atool -x'

alias nvim='sudo nvim -u ~/dotfiles/config/vim/init.vim'
alias vim='nvim -u ~/dotfiles/config/vim/init.vim'
alias reload='source ~/.zshrc'
alias cap_live='ionic cap run android -l --external'

source ~/dotfiles/config/zsh/functions

autoload -Uz compinit -u
compinit -u
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES
