if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

#make QT application use the gnome icon theme
export DESKTOP_SESSION=gnome

xset -dpms s off
xrdb -load dotfiles/xorg/Xresources

start-pulseaudio-x11 &
udiskie &
exec i3 -c dotfiles/i3/config
