if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

#make QT application use the gnome icon theme
export DESKTOP_SESSION=gnome
export XKB_DEFAULT_LAYOUT=de
export XKB_DEFAULT_OPTIONS=caps:escape

xset -dpms s off
xset r rate 200 50
xrdb -load dotfiles/xorg/Xresources
exec i3 -c dotfiles/i3/config
