#!/bin/bash

if [[ $1 = "-w" ]]; then
	BG="$(find ~/dotfiles/Pictures/wbg* -type f -print0 | xargs -0 ls -t | shuf -n1)"
else
	BG="$(find ~/dotfiles/Pictures/bg* -type f -print0 | xargs -0 ls -t | shuf -n1)"
fi

sway output "*" bg "$BG" fill



