#!/bin/bash

INTERFACE=$(nmcli device | grep ethernet | awk '{print $1;}')
IFACE_STATE=$(cat /sys/class/net/$INTERFACE/operstate)

if [ "$IFACE_STATE" = "up" ]; 
	then
		nmcli r wifi off	
	else
		nmcli r wifi on
fi	
